name: Build Android Only

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions: write-all

jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Build Release APK
        run: flutter build apk --release --split-per-abi

      - name: Release
        run: |
          gh release create "${{ github.sha }}" build/app/outputs/flutter-apk/*.apk --title "Auto Build ${{ github.sha }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
